[tools]
bun = "1.3.9"
node = "24"

[tasks.clone-repos]
description = "Clone all team repos into desination folder"
usage = '''
flag "--destination <destination>" help="Pre-existing folder to clone all repoisitories in"
'''
run = 'bun run src/index.ts clone-team-repos --destination=${usage_destination?} --use-sub-folders=true'

[tasks.prs]
description = "Get prs for team"
run = 'bun run src/index.ts prs'

[tasks.repos]
usage = '''
arg "<file>" help="The file to output list of repositories as json to" default="repos.json"
'''
run = 'bun run src/index.ts repos --output=${usage_file}'

[tasks.repos-md]
usage = '''
arg "<file>" help="The file to output the repoisitories to in markdown representation" default="repos.md"
'''
run = 'bun run src/index.ts repos --output=${usage_file} --useMarkdown=true' 

