name: Build and publish library

permissions:
  actions: read
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches: ["main"]
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # https://github.com/oven-sh/setup-bun/releases/tag/v2.1.2
        with:
          bun-version: 1.3.9
      - run: bun install --frozen-lockfile
      - run: bun run tsc
      - run: bun run lint
      - run: bun run build-cli
      - run: bun run sanity-check
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: "https://npm.pkg.github.com"
          scope: "@navikt"
      - run: npm publish
        if: github.ref == 'refs/heads/main'
        working-directory: ./esyfo-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # https://github.com/actions/setup-node/releases/tag/v6.2.0
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: jq --arg version "1.0.$(date +%F-%H%M)" '.version = $version' package.json > updated.json && mv updated.json package.json
        working-directory: ./esyfo-cli
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version esyfo-cli/package.json)" && git push
